from __future__ import annotations

from typing import Any, Awaitable, Callable

from . import control, planning


def register_control_planning_tools(
    *,
    register: Callable[[list[Any]], None],
    make_registration: Callable[..., Any],
    inject_state: Callable[[Callable[..., Awaitable[dict[str, Any]]]], Callable[..., Awaitable[dict[str, Any]]]],
    inject_state_and_harness: Callable[[Callable[..., Awaitable[dict[str, Any]]]], Callable[..., Awaitable[dict[str, Any]]]],
    core_profile: str,
) -> None:
    register(
        [
            make_registration(
                name="task_complete",
                description="Mark task complete and end loop.",
                schema={
                    "type": "object",
                    "properties": {"message": {"type": "string"}},
                    "required": ["message"],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(control.task_complete),
                category="control",
                risk="medium",
                allowed_phases={"explore", "plan", "execute", "verify"},
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="task_fail",
                description="Mark task failed and end loop.",
                schema={
                    "type": "object",
                    "properties": {"message": {"type": "string"}},
                    "required": ["message"],
                    "additionalProperties": False,
                },
                handler=inject_state(control.task_fail),
                category="control",
                risk="medium",
                allowed_phases={"explore", "plan", "execute", "verify"},
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="step_complete",
                description="Mark the active staged-execution step ready for verification.",
                schema={
                    "type": "object",
                    "properties": {"message": {"type": "string"}},
                    "required": ["message"],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(control.step_complete),
                category="control",
                risk="medium",
                allowed_phases={"explore", "plan", "execute", "verify"},
                allowed_modes={"loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="step_fail",
                description="Report that the active staged-execution step cannot be completed.",
                schema={
                    "type": "object",
                    "properties": {"message": {"type": "string"}},
                    "required": ["message"],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(control.step_fail),
                category="control",
                risk="medium",
                allowed_phases={"explore", "plan", "execute", "verify"},
                allowed_modes={"loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="finalize_write_session",
                description="Explicitly finalize the active write session, promoting the staged file to the target path.",
                schema={
                    "type": "object",
                    "properties": {},
                    "required": [],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(control.finalize_write_session),
                category="control",
                risk="medium",
                allowed_phases={"explore", "plan", "execute", "verify"},
                allowed_modes={"loop", "planning", "chat"},
                profiles={core_profile},
            ),
            make_registration(
                name="ask_human",
                description="Request human input and pause loop.",
                schema={
                    "type": "object",
                    "properties": {"question": {"type": "string"}},
                    "required": ["question"],
                    "additionalProperties": False,
                },
                handler=inject_state(control.ask_human),
                category="control",
                risk="medium",
                allowed_phases={"explore", "plan", "execute", "verify"},
                allowed_modes={"loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="loop_status",
                description="Return current loop state summary.",
                schema={
                    "type": "object",
                    "properties": {},
                    "required": [],
                    "additionalProperties": False,
                },
                handler=inject_state(control.loop_status),
                category="control",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="plan_set",
                description="Create or replace the current draft execution plan. Provide the full spec contract: goal, inputs, outputs, constraints, acceptance criteria, implementation plan, and steps. Export fields are only for plan documents, never implementation files.",
                schema={
                    "type": "object",
                    "properties": {
                        "goal": {"type": "string", "description": "High-level objective the plan is trying to achieve."},
                        "summary": {"type": "string", "description": "Optional short context summary for the plan."},
                        "inputs": {"type": "array", "description": "Facts, files, or inputs the implementation will rely on."},
                        "outputs": {"type": "array", "description": "Artifacts, files, or outcomes the plan should produce."},
                        "constraints": {"type": "array", "description": "Rules or limits the implementation must respect."},
                        "acceptance_criteria": {"type": "array", "description": "Checklist items that must be satisfied before task completion."},
                        "implementation_plan": {"type": "array", "description": "Short implementation stages or ordered authoring plan items."},
                        "steps": {
                            "type": "array",
                            "description": "Ordered plan steps. Prefer concise step objects with titles over prose paragraphs.",
                            "items": {"anyOf": [{"type": "string"}, {"type": "object"}]},
                        },
                        "output_path": {"type": "string", "description": "Optional plan document export target. Use only .md, .txt, or .text; never pass implementation paths like .py."},
                        "plan_output_path": {"type": "string", "description": "Alias for output_path. Reserved for plan document exports only."},
                        "output_format": {"type": "string", "enum": ["markdown", "md", "text", "txt"], "description": "Optional plan document format. Use markdown/md or text/txt only."},
                        "plan_output_format": {"type": "string", "enum": ["markdown", "md", "text", "txt"], "description": "Alias for output_format."},
                    },
                    "required": ["goal", "inputs", "outputs", "constraints", "acceptance_criteria", "implementation_plan", "steps"],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(planning.plan_set),
                category="planning",
                risk="low",
                allowed_modes={"planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="plan_step_update",
                description="Update a plan step status during planning or execution.",
                schema={
                    "type": "object",
                    "properties": {
                        "step_id": {"type": "string"},
                        "status": {"type": "string"},
                        "note": {"type": "string"},
                    },
                    "required": ["step_id", "status"],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(planning.plan_step_update),
                category="planning",
                risk="low",
                allowed_modes={"planning", "loop"},
                profiles={core_profile},
            ),
            make_registration(
                name="plan_request_execution",
                description="Pause planning and ask the user to approve execution.",
                schema={
                    "type": "object",
                    "properties": {"question": {"type": "string"}},
                    "required": ["question"],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(planning.plan_request_execution),
                category="planning",
                risk="low",
                allowed_modes={"planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="plan_export",
                description="Write the current plan to disk using the canonical exporter.",
                schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "format": {"type": "string"},
                    },
                    "required": ["path"],
                    "additionalProperties": False,
                },
                handler=inject_state_and_harness(planning.plan_export),
                category="planning",
                risk="low",
                allowed_modes={"planning", "loop"},
                profiles={core_profile},
            ),
        ]
    )
