from __future__ import annotations

from typing import Any, Awaitable, Callable

from . import artifact, data, indexer, indexer_query, search


def register_content_tools(
    *,
    register: Callable[[list[Any]], None],
    make_registration: Callable[..., Any],
    inject_state: Callable[[Callable[..., Awaitable[dict[str, Any]]]], Callable[..., Awaitable[dict[str, Any]]]],
    inject_harness: Callable[[Callable[..., Awaitable[dict[str, Any]]]], Callable[..., Awaitable[dict[str, Any]]]],
    core_profile: str,
    data_profile: str,
    indexer_profile: str,
) -> None:
    register(
        [
            make_registration(
                name="grep",
                description="Search file contents recursively.",
                schema={
                    "type": "object",
                    "properties": {
                        "pattern": {"type": "string"},
                        "path": {"type": "string"},
                        "regex": {"type": "boolean"},
                        "case_sensitive": {"type": "boolean"},
                        "max_results": {"type": "integer"},
                    },
                    "required": ["pattern"],
                    "additionalProperties": False,
                },
                handler=search.grep,
                category="search",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="find_files",
                description="Find files recursively.",
                schema={
                    "type": "object",
                    "properties": {
                        "pattern": {"type": "string"},
                        "path": {"type": "string"},
                        "regex": {"type": "boolean"},
                        "max_results": {"type": "integer"},
                    },
                    "required": ["pattern"],
                    "additionalProperties": False,
                },
                handler=search.find_files,
                category="search",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="json_query",
                description="Run JMESPath query on JSON data.",
                schema={
                    "type": "object",
                    "properties": {"data": {}, "expression": {"type": "string"}},
                    "required": ["data", "expression"],
                    "additionalProperties": False,
                },
                handler=data.json_query,
                category="data",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={data_profile},
            ),
            make_registration(
                name="yaml_read",
                description="Read YAML file into structured data.",
                schema={
                    "type": "object",
                    "properties": {"path": {"type": "string"}},
                    "required": ["path"],
                    "additionalProperties": False,
                },
                handler=data.yaml_read,
                category="data",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={data_profile},
            ),
            make_registration(
                name="artifact_read",
                description="Read stored artifact content by ID. Large artifacts are returned in bounded line chunks; use start_line/end_line for follow-up paging.",
                schema={
                    "type": "object",
                    "properties": {
                        "artifact_id": {"type": "string"},
                        "start_line": {"type": "integer"},
                        "end_line": {"type": "integer"},
                        "max_chars": {"type": "integer"},
                    },
                    "required": ["artifact_id"],
                    "additionalProperties": False,
                },
                handler=inject_state(artifact.artifact_read),
                category="data",
                risk="low",
                allowed_modes={"chat", "loop", "indexer", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="artifact_grep",
                description="Search for a pattern within an artifact and return matching lines with line numbers. Use this to find specific information within large artifacts WITHOUT reading the entire content.",
                schema={
                    "type": "object",
                    "properties": {
                        "artifact_id": {"type": "string"},
                        "query": {"type": "string"},
                        "case_insensitive": {"type": "boolean"},
                        "max_results": {"type": "integer"},
                    },
                    "required": ["artifact_id", "query"],
                    "additionalProperties": False,
                },
                handler=inject_state(artifact.artifact_grep),
                category="data",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="artifact_print",
                description="Print out the full contents of an artifact directly to the user's console/UI without including it in your context window. Use this for extremely large outputs (like full logs) that the user should see, but you only need confirmation of.",
                schema={
                    "type": "object",
                    "properties": {"artifact_id": {"type": "string"}},
                    "required": ["artifact_id"],
                    "additionalProperties": False,
                },
                handler=inject_harness(artifact.artifact_print),
                category="data",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile},
            ),
            make_registration(
                name="index_write_symbol",
                description="Record a source code symbol (class, function) in the project index.",
                schema={
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "kind": {"type": "string"},
                        "file": {"type": "string"},
                        "start_line": {"type": "integer"},
                        "end_line": {"type": "integer"},
                        "signature": {"type": "string"},
                        "docstring_short": {"type": "string"},
                        "parent": {"type": "string"},
                    },
                    "required": ["name", "kind", "file", "start_line", "end_line"],
                    "additionalProperties": False,
                },
                handler=indexer.index_write_symbol,
                category="indexer",
                risk="low",
                allowed_modes={"indexer"},
                profiles={indexer_profile},
            ),
            make_registration(
                name="index_write_reference",
                description="Record a cross-reference between symbols in the project index.",
                schema={
                    "type": "object",
                    "properties": {
                        "to_symbol": {"type": "string"},
                        "call_site_file": {"type": "string"},
                        "from_symbol": {"type": "string"},
                        "call_site_line": {"type": "integer"},
                    },
                    "required": ["to_symbol", "call_site_file"],
                    "additionalProperties": False,
                },
                handler=indexer.index_write_reference,
                category="indexer",
                risk="low",
                allowed_modes={"indexer"},
                profiles={indexer_profile},
            ),
            make_registration(
                name="index_write_import",
                description="Record a module import dependency in the project index.",
                schema={
                    "type": "object",
                    "properties": {
                        "file": {"type": "string"},
                        "imported_from": {"type": "string"},
                        "symbols": {"type": "array", "items": {"type": "string"}},
                        "is_external": {"type": "boolean"},
                    },
                    "required": ["file", "imported_from"],
                    "additionalProperties": False,
                },
                handler=indexer.index_write_import,
                category="indexer",
                risk="low",
                allowed_modes={"indexer"},
                profiles={indexer_profile},
            ),
            make_registration(
                name="index_finalize",
                description="Finalize the indexing process and generate a project manifest.",
                schema={
                    "type": "object",
                    "properties": {},
                    "required": [],
                    "additionalProperties": False,
                },
                handler=indexer.index_finalize,
                category="indexer",
                risk="low",
                allowed_modes={"indexer"},
                profiles={indexer_profile},
            ),
            make_registration(
                name="index_batch_write",
                description="Write multiple indexing records (symbols, references, imports) in a single batch.",
                schema={
                    "type": "object",
                    "properties": {
                        "symbols": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {"type": "string"},
                                    "kind": {"type": "string"},
                                    "file": {"type": "string"},
                                    "start_line": {"type": "integer"},
                                    "end_line": {"type": "integer"},
                                    "signature": {"type": "string"},
                                    "docstring_short": {"type": "string"},
                                    "parent": {"type": "string"},
                                },
                                "required": ["name", "kind", "file"],
                                "additionalProperties": False,
                            },
                        },
                        "references": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "to_symbol": {"type": "string"},
                                    "call_site_file": {"type": "string"},
                                    "from_symbol": {"type": "string"},
                                    "call_site_line": {"type": "integer"},
                                },
                                "required": ["to_symbol", "call_site_file"],
                                "additionalProperties": False,
                            },
                        },
                        "imports": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "file": {"type": "string"},
                                    "imported_from": {"type": "string"},
                                    "symbols": {"type": "array", "items": {"type": "string"}},
                                    "is_external": {"type": "boolean"},
                                },
                                "required": ["file", "imported_from"],
                                "additionalProperties": False,
                            },
                        },
                    },
                    "required": [],
                    "additionalProperties": False,
                },
                handler=indexer.index_batch_write,
                category="indexer",
                risk="low",
                allowed_modes={"indexer"},
                profiles={indexer_profile},
            ),
            make_registration(
                name="index_query_symbol",
                description="Search for symbols in the code index by name or fuzzy pattern.",
                schema={
                    "type": "object",
                    "properties": {"query": {"type": "string"}},
                    "required": ["query"],
                    "additionalProperties": False,
                },
                handler=indexer_query.index_query_symbol,
                category="indexer",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile, indexer_profile},
            ),
            make_registration(
                name="index_get_references",
                description="Retrieve all locations where a specific symbol is referenced.",
                schema={
                    "type": "object",
                    "properties": {"symbol_name": {"type": "string"}},
                    "required": ["symbol_name"],
                    "additionalProperties": False,
                },
                handler=indexer_query.index_get_references,
                category="indexer",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile, indexer_profile},
            ),
            make_registration(
                name="index_get_definition",
                description="Retrieve the file path and line numbers where a symbol is defined.",
                schema={
                    "type": "object",
                    "properties": {"symbol_name": {"type": "string"}},
                    "required": ["symbol_name"],
                    "additionalProperties": False,
                },
                handler=indexer_query.index_get_definition,
                category="indexer",
                risk="low",
                allowed_modes={"chat", "loop", "planning"},
                profiles={core_profile, indexer_profile},
            ),
        ]
    )
