from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class HarnessConfig:
    endpoint: str
    model: str
    phase: str = "explore"
    provider_profile: str = "generic"
    api_key: str | None = None
    tool_profiles: list[str] | None = None
    reasoning_mode: str = "auto"
    thinking_visibility: bool = True
    thinking_start_tag: str = "<think>"
    thinking_end_tag: str = "</think>"
    chat_endpoint: str = "/chat/completions"
    runtime_context_probe: bool = True
    context_limit: int | None = None
    max_prompt_tokens: int | None = None
    max_prompt_tokens_explicit: bool = False
    reserve_completion_tokens: int = 1024
    reserve_tool_tokens: int = 512
    first_token_timeout_sec: int | None = None
    healthcheck_url: str | None = None
    restart_command: str | None = None
    startup_grace_period_sec: int = 20
    max_restarts_per_hour: int = 2
    backend_healthcheck_url: str | None = None
    backend_restart_command: str | None = None
    backend_unload_command: str | None = None
    backend_healthcheck_timeout_sec: int = 5
    backend_restart_grace_sec: int = 20
    summarize_at_ratio: float = 0.8
    recent_message_limit: int = 32
    max_summary_items: int = 3
    max_artifact_snippets: int = 4
    artifact_snippet_token_limit: int = 400
    artifact_summarization_threshold: int = 1560
    multi_file_artifact_snippet_limit: int = 8
    multi_file_primary_file_limit: int = 3
    remote_task_artifact_snippet_limit: int = 8
    remote_task_primary_file_limit: int = 2
    checkpoint_on_exit: bool = False
    checkpoint_path: str | None = None
    graph_checkpointer: str = "memory"
    graph_checkpoint_path: str | None = None
    graph_node_timeout_sec: int = 300
    graph_model_call_timeout_sec: int = 600
    graph_dispatch_tools_timeout_sec: int = 300
    graph_idle_watchdog_sec: int = 300
    graph_recursion_limit: int = 1024
    graph_coding_recursion_limit: int = 2048
    needs_human_timeout_sec: int = 600
    fresh_run: bool = False
    fresh_run_turns: int = 1
    planning_mode: bool = False
    contract_flow_ui: bool = False
    staged_execution_enabled: bool = False
    staged_step_prompt_tokens: int = 4096
    summarizer_endpoint: str | None = None
    summarizer_model: str | None = None
    summarizer_api_key: str | None = None
    run_logger: Any = None
    artifact_start_index: int | None = None
    tool_result_inline_token_limit: int = 250
    artifact_read_inline_token_limit: int = 1024
    strategy_prompt: str | None = None
    strategy: dict[str, Any] | None = None
    indexer: bool = False
    policy: Any = None
    allow_interactive_shell_approval: bool = False
    shell_approval_session_default: bool = False
    loop_guard_enabled: bool = True
    loop_guard_stagnation_threshold: int = 3
    loop_guard_level2_threshold: int = 5
    loop_guard_recent_writes_limit: int = 5
    loop_guard_tail_lines: int = 50
    loop_guard_similarity_threshold: float = 0.9
    loop_guard_cumulative_write_gate: bool = True
    loop_guard_checkpoint_gate: bool = True
    loop_guard_diff_gate: bool = True
    fama_enabled: bool = True
    fama_mode: str = "lite"
    fama_default_ttl_steps: int = 2
    fama_max_active_mitigations: int = 2
    fama_signal_window: int = 8
    fama_done_gate_on_failure: bool = True
    fama_capsule_token_budget: int = 180
    fama_llm_judge_enabled: bool = False
    fama_llm_judge_min_severity: int = 3
    fama_disabled: bool = False
    reflexion_enabled: bool = True
    reflexion_max_items: int = 5
    reflexion_inject_top_k: int = 3
    reflexion_persist_cross_task: bool = False
    reflexion_min_failure_severity: str = "warning"
    subtask_ledger_enabled: bool = True
    subtask_max_active: int = 1
    subtask_max_history: int = 12
    subtask_inject_completed_limit: int = 3
    run_mode: str = "auto"
    tool_plan_runtime_enabled: bool = False
    tool_plan_auto_select: bool = False
    tool_plan_readonly_only: bool = True
    tool_plan_max_steps: int = 6
    tool_plan_max_repair_attempts: int = 1
    schema_validation_max_repair_attempts: int = 2
    tool_plan_observation_token_limit: int = 900
    tool_plan_max_observation_chars_per_step: int = 600
    tool_plan_solver_fresh_output_limit: int = 1200
    tool_plan_allow_web: bool = True
    tool_plan_allow_artifact_read: bool = True
    tool_plan_allow_git: bool = False
    tool_plan_fallback_to_loop_on_invalid_plan: bool = True
    tool_dag_enabled: bool = False
    min_exploration_steps: int = 1
    chunk_mode_min_bytes: int = 4096
    chunk_mode_new_file_only: bool = True
    chunk_mode_supported_models: list[str] = field(default_factory=lambda: ["qwen3.5", "llama3.1", "deepseek-v3"])
    small_model_soft_write_chars: int = 2000
    small_model_hard_write_chars: int = 4000
    new_file_chunk_mode_line_estimate: int = 100
    allow_multi_section_turns_for_small_edits: bool = True
    failed_local_patch_limit: int = 2
    max_repair_steps: int = 3
    enable_write_intent_recovery: bool = True
    enable_assistant_code_write_recovery: bool = True
    write_recovery_min_confidence: str = "high"
    write_recovery_allow_raw_text_targets: bool = True
    tool_dag_max_parallel: int = 4
    tool_dag_timeout_sec: int = 30
    tool_dag_preserve_result_order: bool = True
    rewoo_lane_frames_enabled: bool = False
    rewoo_planner_frame_enabled: bool = False
    rewoo_solver_frame_enabled: bool = False
    rewoo_refiner_frame_enabled: bool = False
    rewoo_frame_token_budget: int = 1200
    solver_refine_enabled: bool = False
    solver_refine_max_passes: int = 1
    solver_refine_on_final_answer: bool = True
    solver_refine_on_patch_plan: bool = True
    solver_refine_on_task_complete: bool = True
    solver_refine_token_budget: int = 700
    test_time_scaling_enabled: bool = False
    test_time_scaling_runtimes: list[str] = field(default_factory=lambda: ["staged_execution"])
    test_time_scaling_trigger: str = "retry_or_explicit"
    test_time_scaling_max_candidates: int = 3
    test_time_scaling_min_candidates: int = 2
    test_time_scaling_policy: str = "proposal_then_execute"
    test_time_scaling_strategy: str = "diverse_nudges"
    test_time_scaling_score_threshold: float = 0.85
    test_time_scaling_parallel_max: int = 1
    test_time_scaling_timeout_sec: int = 120
    test_time_scaling_mutating_parallel_enabled: bool = False
    test_time_scaling_all_fail_action: str = "fallback_normal_retry"
    escalation_enabled: bool = False
    escalation_expose_tool: bool = True
    escalation_auto_trigger: bool = False
    escalation_endpoint: str | None = None
    escalation_model: str | None = None
    escalation_provider_profile: str = "auto"
    escalation_api_key: str | None = None
    escalation_api_key_env: str | None = None
    escalation_chat_endpoint: str = "/chat/completions"
    escalation_max_prompt_chars: int = 48000
    escalation_max_response_tokens: int = 1600
    escalation_temperature: float = 0.2
    escalation_timeout_sec: int = 120
    escalation_max_per_task: int = 2
    escalation_cooldown_turns: int = 2
    escalation_repeated_failure_threshold: int = 2
    escalation_require_tool_plan_evidence: bool = True
    escalation_redact_secrets: bool = True
    verbose: bool = False


