"""
aho/mock_tools.py
-----------------
Mock tool handlers for the AHO execution sandbox.

These simulate real-world tool calls (weather, clothing, long-context documents)
so that the harness can run fully offline, making strategy evaluation fast and
deterministic.

The Harness is configured to inject these tools into its registry via a
custom build_registry call in harness_runner.py — the existing
src/smallctl/tools/register.py is not modified.

Context-pressure tools
----------------------
`long_context_lookup`  — returns a ~3 000-token reference document to simulate
                         retrieving a verbose policy/RAG chunk.
`summarize_report`     — returns a separate ~2 500-token analyst report, adding
                         a second large injection to the conversation history.

Used by the 'long_context_stress' task in harness_config.json to evaluate how
well a strategy handles content that pushes past the 8 K context limit.
"""

from __future__ import annotations

import random
from typing import Any

# ---------------------------------------------------------------------------
# Deterministic seed per (trial_id, call_index) for reproducibility
# ---------------------------------------------------------------------------

_WEATHER_OPTIONS = [
    {"condition": "rainy", "temperature_c": 12, "wind_kmh": 25},
    {"condition": "sunny", "temperature_c": 28, "wind_kmh": 8},
    {"condition": "snowy", "temperature_c": -3, "wind_kmh": 15},
    {"condition": "cloudy", "temperature_c": 18, "wind_kmh": 12},
    {"condition": "stormy", "temperature_c": 10, "wind_kmh": 60},
]

_CLOTHING_MAP: dict[str, list[str]] = {
    "rainy": ["umbrella", "raincoat", "waterproof boots"],
    "sunny": ["t-shirt", "sunscreen", "sunglasses"],
    "snowy": ["coat", "gloves", "thermal socks"],
    "cloudy": ["jacket", "jeans", "light sweater"],
    "stormy": ["heavy raincoat", "umbrella", "rubber boots"],
}


async def weather_lookup(*, city: str, trial_seed: int = 0, **_: Any) -> dict[str, Any]:
    """
    Returns mock weather for a city.
    trial_seed is injected by harness_runner to make trials independently random
    but reproducible for a given seed.
    """
    rng = random.Random(trial_seed)
    weather = rng.choice(_WEATHER_OPTIONS)
    return {
        "success": True,
        "output": {
            "city": city,
            "condition": weather["condition"],
            "temperature_c": weather["temperature_c"],
            "wind_kmh": weather["wind_kmh"],
        },
        "error": None,
        "metadata": {"source": "mock", "trial_seed": trial_seed},
    }


async def clothing_suggest(*, condition: str, **_: Any) -> dict[str, Any]:
    """
    Returns a clothing suggestion based on weather condition.
    The ground_truth checker looks for any of these keywords in the final answer.
    """
    options = _CLOTHING_MAP.get(condition.lower(), ["a comfortable outfit"])
    suggestion = options[0]
    return {
        "success": True,
        "output": {
            "condition": condition,
            "suggestion": suggestion,
            "alternatives": options[1:],
        },
        "error": None,
        "metadata": {"source": "mock"},
    }


# ---------------------------------------------------------------------------
# Context-pressure tools  (force 8 K context overflow)
# ---------------------------------------------------------------------------

# ~3 000-token reference document (verbose policy text)
_LONG_DOCUMENT = """\
=== GLOBAL CLIMATE POLICY REFERENCE DOCUMENT v4.2 ===
Generated by: ClimatePolicyBot  |  Last updated: 2026-01-01

SECTION 1 — OVERVIEW OF INTERNATIONAL CLIMATE FRAMEWORKS

The Paris Agreement, adopted in December 2015 under the United Nations Framework
Convention on Climate Change (UNFCCC), represents the most comprehensive
multilateral treaty on climate action to date.  Participating nations (currently
195 parties) commit to Nationally Determined Contributions (NDCs) that are
reviewed and strengthened every five years in a 'ratchet mechanism'.

Key temperature targets set by the Agreement:
  • Hold global average temperature increase to well below 2 °C above
    pre-industrial levels.
  • Pursue efforts to limit that increase to 1.5 °C, recognising that
    this would significantly reduce climate-change related risks.

Financing commitments:
  Developed countries pledged USD 100 billion per year to developing nations
  through 2025 under the Green Climate Fund (GCF). Post-2025 commitments under
  the New Collective Quantified Goal (NCQG) are still under negotiation as of
  the COP29 proceedings in Baku (November 2024).

SECTION 2 — REGIONAL BREAKDOWN: EUROPE

2.1 European Union — Fit for 55 Package
  Target: Reduce net greenhouse-gas emissions by at least 55 % by 2030
          relative to 1990 levels; achieve climate neutrality by 2050.
  Key policies:
    • EU Emissions Trading System (EU ETS) — Phase IV (2021-2030) tightens
      the annual linear reduction factor from 1.74 % to 2.2 %.
    • Carbon Border Adjustment Mechanism (CBAM) — Full implementation from
      January 2026; covers iron/steel, cement, aluminium, fertilisers,
      electricity, and hydrogen.
    • REPowerEU — Targets 45 % share of renewables in total energy mix by
      2030, up from the previous 40 % goal.
    • Energy Efficiency Directive (EED) — Binding target of 11.7 % reduction
      in final energy consumption by 2030 vs. PRIMES 2020 reference scenario.
  Methane Regulation:
    New rules require oil, gas, and coal sector operators to measure, report,
    and verify (MRV) methane emissions quarterly by 2025, with limits from
    2027 onwards.

2.2 United Kingdom — Net Zero Strategy
  Trajectory: Six carbon budgets already legislated; CB6 covers 2033-2037
  and requires a 78 % reduction from 1990 levels.
  Flagship programmes:
    • Contracts for Difference (CfD) — Offshore wind capacity target of
      50 GW by 2030.  Allocation Round 6 (AR6) announced in Q1 2026.
    • Boiler Upgrade Scheme (BUS) — £7 500 grants for air-source heat pumps.
    • ZEV Mandate — 22 % of new cars sold in 2024 must be zero-emission;
      rising to 80 % by 2030 and 100 % by 2035.

SECTION 3 — REGIONAL BREAKDOWN: NORTH AMERICA

3.1 United States — Inflation Reduction Act (IRA) 2022
  Total climate investment: Approximately USD 370 billion over ten years.
  Major provisions:
    • Production Tax Credit (PTC, §45) — Extended & expanded for wind, solar,
      geothermal, and new clean electricity sources (§45Y).
    • Investment Tax Credit (ITC, §48) — Expanded to include standalone
      storage, biogas, and microgrid controllers.
    • Advanced Manufacturing Production Credit (§45X) — Per-unit credits for
      domestically manufactured solar cells, wind components, batteries, and
      critical minerals.
    • Clean Vehicle Credits (§30D / §25E) — Up to USD 7 500 for new EVs;
      income and MSRP caps apply.  Battery component requirements
      progressively tighten 2024–2029.
    • Hydrogen Production Credit (§45V) — Up to USD 3/kg for zero-carbon
      hydrogen; lifecycle emissions threshold < 0.45 kg CO₂e/kg H₂.
  Implementation status (as of March 2026):
    Treasury / IRS have finalised rules for §45V, §45X, and §48.  Rules for
    §45Y are still in proposed rulemaking.  Total IRA-attributed investment
    announcements exceed USD 265 billion.

3.2 Canada — 2030 Emissions Reduction Plan
  Target: 40–45 % below 2005 levels by 2030; net zero by 2050.
  Instruments:
    • Federal Carbon Pricing — Fuel charge rises by CAD 15/tonne per year;
      currently CAD 80/tonne as of April 2024.
    • Clean Electricity Regulations — Proposed net-zero grid by 2035.
    • Clean Fuels Regulations — Lifecycle carbon intensity standard for
      liquid fuels, reducing CI by 15 % below 2016 baseline by 2030.

SECTION 4 — REGIONAL BREAKDOWN: ASIA-PACIFIC

4.1 China — Dual Carbon Goals
  Peak emissions: Before 2030.
  Carbon neutrality: Before 2060.
  Key mechanisms:
    • National ETS (CETS) — World's largest carbon market by covered
      emissions (~4 Gt CO₂/yr in power sector); price ~¥95/t as of Q4 2025.
      Coverage expected to expand to steel and cement in 2026.
    • Renewable energy targets: 1 200 GW of wind and solar by 2030;
      already surpassed 1 100 GW in 2024.
    • NEV market share: 25 % of new car sales in 2025 (achieved ahead of
      schedule); target 40 % by 2030.

4.2 Japan — GX (Green Transformation) Plan
  Investment: JPY 150 trillion (~USD 1 trillion) over 10 years.
  GX Emissions Trading System (GX-ETS) launched April 2023 (voluntary);
  mandatory cap-and-trade from FY2026.
  Nuclear: Policy reversal — lifetime extensions and restart programme for
  existing plants; advanced reactors eligible for JPY 1 trillion support.

4.3 India — Panchamrit Targets
  • 500 GW non-fossil electricity capacity by 2030.
  • 50 % of cumulative electricity from non-fossil sources by 2030.
  • Reduce emissions intensity of GDP by 45 % from 2005 by 2030.
  • Net zero by 2070.
  Carbon market: Carbon Credit Trading Scheme (CCTS) operational from 2024;
  aligned with BEE's Perform, Achieve and Trade (PAT) scheme.

SECTION 5 — TECHNOLOGY BENCHMARKS (2025 SNAPSHOT)

  Technology            LCOE (USD/MWh)     Cost trend
  ─────────────────── ─────────────────── ──────────────────────
  Utility Solar (PV)       28–42           −90 % since 2010
  Onshore Wind             26–38           −70 % since 2010
  Offshore Wind            68–95           −60 % since 2015
  Li-ion Battery (4h)      120–160/MWh     −88 % since 2010
  Green Hydrogen           3.5–7.0 USD/kg  Rapidly falling
  Blue Hydrogen            1.5–2.5 USD/kg  Stable
  Nuclear (new build)      90–180          Rising due to labour
  CCUS (point-source)      60–120 USD/tCO₂ Early commercial stage

SECTION 6 — CRITICAL MINERALS SUPPLY CHAIN

The energy transition is intensely mineral-intensive:
  • Lithium demand projected to grow 40× by 2040 (IEA CMS 2023).
  • Cobalt demand  grows 20×; Democratic Republic of Congo supplies ~70 %.
  • Nickel, manganese, graphite also face potential supply constraints.
  Notable policy responses:
    EU Critical Raw Materials Act (CRMA) — In force from May 2024.
    US Mineral Security Partnership (MSP) — 14-country coalition for
    diversified supply chains.
    IRA §45X and DOE Loan Programs Office (LPO) support domestic
    battery processing.

SECTION 7 — LOSS AND DAMAGE FUND

Established at COP27 (Sharm el-Sheikh, 2022); operationalised at COP28
(Dubai, 2023).  Initial pledges: ~USD 700 million — far below estimated
annual needs of USD 400 billion by 2030 (V20 group estimate).
Hosted by the World Bank for an interim period of four years.

[END OF DOCUMENT]
"""

# ~2 500-token analyst report
_ANALYST_REPORT = """\
=== QUARTERLY CARBON MARKETS ANALYST REPORT — Q4 2025 ===
Prepared by: QuantCarbon Research  |  Confidential

EXECUTIVE SUMMARY

Carbon markets globally experienced significant volatility in Q4 2025 driven
by geopolitical uncertainty, energy-price swings, and evolving Article 6
implementation rules.  EU ETS allowances (EUAs) averaged €58.40/t across the
quarter — down 12 % YoY — as mild winter temperatures reduced energy demand
and thus compliance buying pressure.  Meanwhile, voluntary carbon markets
(VCM) continued their recovery following the Integrity Council for the
Voluntary Carbon Market (ICVCM) Core Carbon Principles roll-out.

SECTION A — EU ETS: PRICE & VOLUME ANALYSIS

A.1  Spot and Futures
  EUA Dec-25 futures settled at €56.10/t on 31 Dec 2025 (ICE Endex).
  Daily trading volume averaged 28.6 million EUAs, roughly in line with the
  5-year average.  Auction clearing prices ranged from €52.90 to €63.75.

A.2  Free Allocation Update
  Phase IV (2021-2030) free allocation began tapering in 2026 for CBAM-
  covered sectors.  Steel producers in Germany and Poland received ~15 %
  fewer free allowances compared to 2025, accelerating hedging activity.

A.3  CBAM Impact on Trade Flows
  Early data indicate a ~3 % reduction in imports of CBAM-covered goods from
  non-Article 6 jurisdictions in Q4 2025.  Chinese steel producers have begun
  investing in EAF (electric arc furnace) technology in anticipation of full
  CBAM implementation.

SECTION B — VOLUNTARY CARBON MARKET (VCM)

B.1  Issuance & Retirement Trends
  Total retirements in 2025: ~210 MtCO₂e (Trove Intelligence estimate) —
  essentially flat vs 2024 after three years of post-scandal contraction.
  Nature-based solutions (NBS) still dominate at ~45 % of issuances, though
  tech-based removals (DACCS, enhanced weathering, biochar) are growing fast,
  now ~8 % of issuances vs. 2 % in 2022.

B.2  Pricing by Category (spot, USD/tCO₂)
  Category                   Q4 2025 mean   Q4 2024 mean
  ─────────────────────────  ─────────────  ─────────────
  REDD+ (forestry avoid.)        3.20           2.85
  IFM (improved mgmt)            6.10           5.40
  Afforestation / Reforest.      7.80           7.20
  Cookstoves / HFC destroy.      4.50           3.90
  Direct Air Capture (DAC)     180–320        160–280
  Biochar                       85–95           70–80
  Enhanced Weathering            55–75          45–65

B.3  ICVCM CCP Label
  As of Q4 2025, 22 methodologies have been approved under the Core Carbon
  Principles (CCP) framework.  A further 14 are under review.  CCP-labelled
  credits trade at a 15–30 % premium to non-labelled equivalents.

SECTION C — ARTICLE 6 IMPLEMENTATION

COP29 (Baku, Nov 2024) finalised the supervisory body rules for Art. 6.4
mechanism credits (A6.4ERs), unblocking the international carbon credit
market.  Key developments:
  • First batch of A6.4ER methodologies approved for renewable energy,
    cooking, and biochar.  Forestry methodologies expected H1 2026.
  • Corresponding adjustments (CAs): Host countries must apply CAs to
    credits sold to Art. 6.2 bilateral buyers, permanently retiring an
    equivalent quantity from their national NDC accounting.
  • Switzerland–Ghana bilateral deal — first fully operational Art. 6.2
    transaction; 200 000 tCO₂e issued, price undisclosed.

SECTION D — REGIONAL MARKET HIGHLIGHTS

D.1  China CETS
  Annual compliance cycle for 2024 completed Jan 2025; compliance rate 99.8 %.
  Price averaged ¥93/t in Q4.  Expansion to steel and cement officially
  announced for the 2026 compliance period.  Coverage would add ~1.5 Gt/yr.

D.2  California Cap-and-Trade
  Q4 2025 quarterly auction cleared at USD 31.54/t (allowance floor + buffer).
  Linkage with Quebec continues; combined market covers ~80 % of state GHG.

D.3  RGGI (US Northeast)
  Q4 2025 auction: USD 17.92/t.  Connecticut rejoined programme Sept 2024.
  New York finalising allowance retirement of banked credits to strengthen
  programme stringency.

SECTION E — OUTLOOK Q1 2026

Expect upward EUA price pressure if the La Niña weather pattern drives a cold
European winter in January-February.  VCM likely to see continued bifurcation
between high-quality CCP credits and commoditised avoidance offsets.
Article 6 pipeline activity anticipated to accelerate significantly once
forestry methodologies are finalised (est. H1 2026).

[END OF REPORT — QuantCarbon Research, Jan 2026]
"""


async def long_context_lookup(
    *, 
    topic: str, 
    distilled: bool = True,  # CHANGED: Default to True for inline results
    query: str | None = None,  # NEW: Query string for context-aware extraction
    min_confidence: float = 0.5,  # NEW: Minimum confidence threshold (lowered for demo)
    **_: Any
) -> dict[str, Any]:
    """
    Returns KEY FACTS from climate policy document (~80 tokens).
    
    Phase 3: Uses smart extraction with validation and fallback.
    Set distilled=False only if you need the full verbose document (~3000 tokens).
    """
    # Import here to avoid circular dependency
    from aho.fact_extractor import extract_key_facts, QueryContext, FactExtractor
    from aho.fact_validator import FactValidator, InlineResultValidator
    
    # Always extract facts first (for metadata)
    extractor = FactExtractor()
    context = QueryContext(query=query or f"Find {topic} information", topic="climate")
    facts = extractor.extract_smart(_LONG_DOCUMENT, context, max_facts=5)
    
    # Phase 3: Validate extracted facts
    validator = FactValidator()
    validation = validator.validate(facts, domain="climate_policy")
    
    # Check if we should use inline or fallback to full document
    inline_validator = InlineResultValidator(min_confidence=min_confidence)
    
    if facts:
        facts_output = extractor.format_inline(facts)
        structured = extractor.format_structured(facts)
    else:
        facts_output = "KEY FACTS:\n• No specific facts extracted for this query\n• Document contains climate policy information"
        structured = {}
    
    # Validate the inline result
    result_check = inline_validator.validate_inline_result(
        inline_output=facts_output,
        facts=facts,
        domain="climate_policy",
        metadata={"token_estimate": len(facts_output.split())},
    )
    
    # Phase 3: Fallback to full document if validation fails
    if distilled and result_check["recommendation"] == "use_full_document":
        # Return full document with warning
        return {
            "success": True,
            "output": _LONG_DOCUMENT,
            "error": None,
            "metadata": {
                "source": "mock_policy_db",
                "topic": topic,
                "document_title": "Global Climate Policy Reference Document v4.2",
                "token_estimate": 3100,
                "distilled": False,
                "fallback_reason": "low_confidence",
                "validation": result_check,
                "note": "Fell back to full document due to low extraction confidence. Use distilled=False explicitly if you need the full document.",
            },
        }
    
    # Return inline results (either approved or user explicitly wants distilled)
    if not distilled:
        return {
            "success": True,
            "output": _LONG_DOCUMENT,
            "error": None,
            "metadata": {
                "source": "mock_policy_db",
                "topic": topic,
                "document_title": "Global Climate Policy Reference Document v4.2",
                "token_estimate": 3100,
                "distilled": False,
            },
        }
    
    # Return validated inline results
    return {
        "success": True,
        "output": facts_output,
        "error": None,
        "metadata": {
            "source": "mock_policy_db",
            "topic": topic,
            "document_title": "Global Climate Policy Reference Document v4.2",
            "token_estimate": len(facts_output.split()),  # Approximate
            "distilled": True,
            "extraction_topic": topic,
            "query": query,
            "extracted_facts": structured,
            "fact_count": len(facts),
            "validation": validation,
            "confidence": validation["confidence"],
            "passed_validation": result_check["approved"],
        },
    }


async def summarize_report(
    *, 
    subject: str, 
    distilled: bool = True,  # CHANGED: Default to True for inline results
    query: str | None = None,  # NEW: Query string for context-aware extraction
    min_confidence: float = 0.5,  # NEW: Minimum confidence threshold (lowered for demo)
    **_: Any
) -> dict[str, Any]:
    """
    Returns KEY FACTS from analyst report (~65 tokens).
    
    Phase 3: Uses smart extraction with validation and fallback.
    Set distilled=False only if you need the full verbose report (~2500 tokens).
    """
    # Import here to avoid circular dependency
    from aho.fact_extractor import extract_key_facts, QueryContext, FactExtractor
    from aho.fact_validator import FactValidator, InlineResultValidator
    
    # Always extract facts first (for metadata)
    extractor = FactExtractor()
    context = QueryContext(query=query or f"Find {subject} information", topic="carbon")
    facts = extractor.extract_smart(_ANALYST_REPORT, context, max_facts=6)
    
    # Phase 3: Validate extracted facts
    validator = FactValidator()
    validation = validator.validate(facts, domain="carbon_markets")
    
    # Check if we should use inline or fallback to full document
    inline_validator = InlineResultValidator(min_confidence=min_confidence)
    
    if facts:
        facts_output = extractor.format_inline(facts)
        structured = extractor.format_structured(facts)
    else:
        facts_output = "KEY FACTS:\n• No specific facts extracted for this query\n• Report contains carbon market information"
        structured = {}
    
    # Validate the inline result
    result_check = inline_validator.validate_inline_result(
        inline_output=facts_output,
        facts=facts,
        domain="carbon_markets",
        metadata={"token_estimate": len(facts_output.split())},
    )
    
    # Phase 3: Fallback to full document if validation fails
    if distilled and result_check["recommendation"] == "use_full_document":
        return {
            "success": True,
            "output": _ANALYST_REPORT,
            "error": None,
            "metadata": {
                "source": "mock_analyst_db",
                "subject": subject,
                "report_title": "Quarterly Carbon Markets Analyst Report — Q4 2025",
                "token_estimate": 2500,
                "distilled": False,
                "fallback_reason": "low_confidence",
                "validation": result_check,
                "note": "Fell back to full document due to low extraction confidence.",
            },
        }
    
    # Return inline results (either approved or user explicitly wants distilled)
    if not distilled:
        return {
            "success": True,
            "output": _ANALYST_REPORT,
            "error": None,
            "metadata": {
                "source": "mock_analyst_db",
                "subject": subject,
                "report_title": "Quarterly Carbon Markets Analyst Report — Q4 2025",
                "token_estimate": 2500,
                "distilled": False,
            },
        }
    
    # Return validated inline results
    return {
        "success": True,
        "output": facts_output,
        "error": None,
        "metadata": {
            "source": "mock_analyst_db",
            "subject": subject,
            "report_title": "Quarterly Carbon Markets Analyst Report — Q4 2025",
            "token_estimate": len(facts_output.split()),  # Approximate
            "distilled": True,
            "extraction_topic": "carbon",
            "query": query,
            "extracted_facts": structured,
            "fact_count": len(facts),
            "validation": validation,
            "confidence": validation["confidence"],
            "passed_validation": result_check["approved"],
        },
    }


async def review_draft(
    *,
    draft: str,
    matching_keywords: list[str] | None = None,
    **_: Any,
) -> dict[str, Any]:
    """
    Mandatory pre-flight check. Use this to review your synthesis draft before
    calling task_complete. You must explicitly list keywords from the task
    requirements that are addressed in your draft.
    """
    return {
        "success": True,
        "output": {
            "status": "reviewed",
            "keywords_validated": matching_keywords or [],
            "message": "Draft passed pre-flight check. You may now proceed to task_complete.",
        },
        "error": None,
        "metadata": {"source": "mock"},
    }
